services:
  - type: web
    name: websocket-server
    runtime: node
    buildCommand: |
      cd server
      rm -rf node_modules package-lock.json
      npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FORWARD_TO_NUMBER
        value: +918825190385
    healthCheckPath: /health